### ISSUE TITLE
Icons needed

### ISSUE THREAD

**Issue by CaddyDz** [CaddyDz/English#1]
Need two non-copyrighted free 20*20 pixel PNG icons that represents a search!  
A loop would be perfect
One of them should be black and the other one white 
The icons should be placed under a meaningful names in the /img folder
then referenced to the style.css file on line 42 and line 59 on the time of writing this issue respectively.
You can find a /* TODO */ comment above the lines though.

**Comment by 5nai3r** [comment]
Donne

**Comment by 13makk37** [comment]
ask abdou sellali to make one !

**Comment by CaddyDz** [comment]
Thanks @13makk37  but @5nai3r already did it.
I'm closing this issue
