### ISSUE TITLE
Developer unfindable

### ISSUE THREAD

**Issue by Githubyte** [CaddyDz/English#8]
No trace for the developer in social media ..

**Comment by CaddyDz** [comment]
xD is even unfound a word ? 
and I'm available on [Stack Exchange](http://stackexchange.com/users/7327579/caddy) and [Reddit](https://www.reddit.com/user/caddydz/) and [Live Coding TV](https://www.livecoding.tv/caddy/) and [Discord](caddy#9354) and [Twitter](https://twitter.com/TBITWMESTERY)
Just tell me if you needed me anywhere else but fb cuz I'm not going back to a bunch of idiots

**Comment by Githubyte** [comment]
OK

**Comment by Githubyte** [comment]
I'm too looking for better ways, do you want to create a vk.com account? ...there is this list I'm trying to find the most secure...
https://en.wikipedia.org/wiki/I2P
https://en.wikipedia.org/wiki/Ring_(software)
https://en.wikipedia.org/wiki/Tox_(protocol)
https://en.wikipedia.org/wiki/Comparison_of_instant_messaging_clients
Wikipedia though is not a good source of information, can't find a good encrypted p2p with no logs Russian messenger ...

**Comment by CaddyDz** [comment]
If you want the most private secure messaging app then make your own.
You can create your own encrypting algorithm based on any encryption you'd like (I personally prefer Triple DES and BASE64) or use Gnu Privacy Guard to encrypt your communications and set a bot to decrypt it using the private key you provide after checking the pub of course.

**Comment by Githubyte** [comment]
Can't access my reddit account, and it would be easier if we used something else to communicate ..choose us something , I also plan to invite some friends to the alternative way so I gradually quit fb  ...I need a quick way , the app would take some time to create ..

**Comment by CaddyDz** [comment]
why not creating an IRC channel for the project on hex chat ?

**Comment by Githubyte** [comment]
Go ahead and delete this Issue.

**Comment by CaddyDz** [comment]
Join #englishdz IRC channel on FreeNode
[![IRC](https://i.imgur.com/D0y4q58.png)](https://en.wikipedia.org/wiki/XChat)
